parameters:
    command_chain_log_file: "command_chain.log"

services:

    chaincommandbundle.event.commandsubscriber:
        class: ChainCommandBundle\Event\CommandSubscriber
        arguments:
            - "@chaincommandbundle.manager"
        tags:
            - { name: kernel.event_subscriber }

    chaincommandbundle.manager:
        class: ChainCommandBundle\Manager\ChainCommandManager
        arguments:
            - "@chaincommandbundle.chain"
            - "@chaincommandbundle.logger"

    chaincommandbundle.chain:
        class: ChainCommandBundle\Chain\Chain

    chaincommandbundle.logger:
        class: Symfony\Bridge\Monolog\Logger
        public: false
        arguments:
            - "command_chain"
        calls:
            - ["pushHandler", ["@chaincommandbundle.logger.handler"]]

    chaincommandbundle.logger.handler:
        class: Monolog\Handler\StreamHandler
        arguments:
            - "%kernel.logs_dir%/%command_chain_log_file%"
            - 200